package com.example.cycles.interfaces;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * OrderService: Part of cycle with PaymentProcessor.
 * 
 * This class should implement the interface generated by InterfaceExtractionStrategy.
 * The interface should contain all methods called by PaymentProcessor.
 */
@Service
public class OrderService {

    @Autowired
    private PaymentProcessor paymentProcessor;

    // Methods called by PaymentProcessor - should be in interface
    public String getOrderDetails(Long orderId) {
        return "Order-" + orderId;
    }

    public void updateOrderStatus(Long orderId, String status) {
        System.out.println("Order " + orderId + " status updated to: " + status);
    }

    public void addPaymentNote(Long orderId, String note) {
        System.out.println("Payment note added to order " + orderId + ": " + note);
    }

    public void notifyCustomer(Long orderId, String message) {
        System.out.println("Notifying customer for order " + orderId + ": " + message);
    }

    public Double getOrderTotal(Long orderId) {
        return 100.0;  // Mock value
    }

    public boolean validateOrder(Long orderId) {
        return true;  // Mock value
    }

    public void lockOrder(Long orderId) {
        System.out.println("Order " + orderId + " locked");
    }

    public String getOrderMetadata(Long orderId) {
        return "metadata-" + orderId;
    }

    public String getOrderStatus(Long orderId) {
        return "PROCESSING";
    }

    public void cancelOrder(Long orderId) {
        System.out.println("Cancelling order: " + orderId);
    }

    // Method NOT called by PaymentProcessor - should NOT be in interface
    public void archiveOrder(Long orderId) {
        System.out.println("Archiving order: " + orderId);
    }
}

